distributable:
  url: https://github.com/viaduct-ai/kustomize-sops/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: viaduct-ai/kustomize-sops

dependencies:
  go.dev: ^1.22

build:
  dependencies:
    go.dev: ^1.22
  script:
    - go mod download
    - go build -o {{prefix}}/bin/ksops

provides:
  - bin/ksops

test: ksops