distributable:
  url: https://github.com/viaduct-ai/kustomize-sops/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: viaduct-ai/kustomize-sops

dependencies:
  go.dev: ^1.22

build:
  dependencies:
    go.dev: ^1.22
  script:
    - go mod download
    - go build -v -trimpath -ldflags="$GO_LDFLAGS" -o {{prefix}}/bin/ksops
  env:
    GO_LDFLAGS:
      - -s
      - -w
      - -buildmode=pie

provides:
  - bin/ksops

test: command -v ksops
